In [1]:
import numpy as np  #always import when using numpy

In [3]:
#identity matrix:

In [5]:
array_eye = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
array_eye1 = np.eye(3)
array_eye1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
#to create the array of numbers use numpy method arange:
array_of_numbers = np.arange(1,20)  #20 here is exclusive
array_of_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
#req : create an even number array till 30

In [10]:
array_of_evens = np.arange(2,30,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [11]:
#req: Create a simple aray with 6 numbers

In [12]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [14]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [15]:
#(x) --> single dimenion. (x,y)---> two dimensions. (x,y,z)---> Three dimensions

In [16]:
#to understand how many dimensions

In [17]:
x.shape   #will give is the dimensions

(6,)

In [18]:
y = np.arange(6).reshape(2,3)  #impo step 2*3 = 6. i.e row *colunm = number of data points
y

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
y.shape  #two dimensions

(2, 3)

In [21]:
#shape is used to find out the dimensions of the data
#reshape will change the structure of the data. i.e define the matrix as you want 

In [22]:
z = np.arange(12).reshape(2,3,2) #2*3*2 = 12
z

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [23]:
z.shape  #here is in 3 dimensional matrix

(2, 3, 2)

In [24]:
z = np.arange(12).reshape(6,2)
z

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])